name: remindme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  intl:
  async:
  url_launcher:

  get:
  get_storage:
  rive:

  firebase_core: ^2.24.2
  firebase_core_web:
  firebase_auth: ^4.16.0
  firebase_auth_web:
  cloud_firestore:
  cloud_firestore_web:
  firebase_storage:
  firebase_storage_web:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/animations/

